import { IModel } from "@/types/model"

export const models: IModel[] = [
  // OpenAI
  {
    name: "4o",
    baseModel: "4o",
    APIName: "gpt-4o",
    provider: "OpenAI",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: false,
      fileUpload: false,
    },
  },
  {
    name: "4o Mini",
    baseModel: "4o",
    variant: "Mini",
    APIName: "gpt-4o-mini",
    provider: "OpenAI",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: false,
      fileUpload: false,
    },
  },
  {
    name: "4.1",
    baseModel: "4.1",
    variant: "",
    APIName: "gpt-4.1",
    provider: "OpenAI",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: false,
      fileUpload: false,
    },
  },
  {
    name: "4.1 Mini",
    baseModel: "4.1",
    variant: "Mini",
    APIName: "gpt-4.1-mini",
    provider: "OpenAI",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: false,
      fileUpload: false,
    },
  },
  {
    name: "4.1 Nano",
    baseModel: "4.1",
    variant: "Nano",
    APIName: "gpt-4.1-nano",
    provider: "OpenAI",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: false,
      fileUpload: false,
    },
  },
  {
    name: "o3",
    baseModel: "o3",
    variant: "",
    APIName: "o3",
    provider: "OpenAI",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: true,
      fileUpload: false,
    },
  },
  {
    name: "o3 Mini",
    baseModel: "o3",
    variant: "Mini",
    APIName: "o3-mini",
    provider: "OpenAI",
    capabilities: {
      search: false,
      imageUpload: false,
      reasoning: true,
      fileUpload: false,
    },
  },
  {
    name: "o4 Mini",
    baseModel: "o4",
    variant: "Mini",
    APIName: "o4-mini",
    provider: "OpenAI",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: true,
      fileUpload: false,
    },
  },
  // Google
  {
    name: "2.0 Flash",
    baseModel: "2.0",
    variant: "Flash",
    APIName: "gemini-2.0-flash",
    provider: "Google",
    capabilities: {
      search: true,
      imageUpload: true,
      reasoning: false,
      fileUpload: true,
    },
  },
  {
    name: "2.0 Flash Lite",
    baseModel: "2.0",
    variant: "Flash Lite",
    APIName: "gemini-2.0-flash-lite",
    provider: "Google",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: false,
      fileUpload: true,
    },
  },
  {
    name: "2.5 Flash",
    baseModel: "2.5",
    variant: "Flash",
    APIName: "gemini-2.5-flash-preview-05-20",
    provider: "Google",
    capabilities: {
      search: true,
      imageUpload: true,
      reasoning: false,
      fileUpload: true,
    },
  },
  {
    name: "2.5 Pro",
    baseModel: "2.5",
    variant: "Pro",
    APIName: "gemini-2.5-pro-preview-05-06",
    provider: "Google",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: true,
      fileUpload: true,
    },
  },
  // Anthropic
  {
    name: "3 Haiku",
    baseModel: "3",
    variant: "Haiku",
    APIName: "claude-3-haiku-20240307",
    provider: "Anthropic",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: false,
      fileUpload: true,
    },
  },
  {
    name: "3.5 Sonnet",
    baseModel: "3.5",
    variant: "Sonnet",
    APIName: "claude-3-5-sonnet-latest",
    provider: "Anthropic",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: false,
      fileUpload: true,
    },
  },
  {
    name: "3.7 Sonnet",
    baseModel: "3.7",
    variant: "Sonnet",
    APIName: "claude-3-7-sonnet-latest",
    provider: "Anthropic",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: true,
      fileUpload: true,
    },
  },
  {
    name: "4.0 Sonnet",
    baseModel: "4.0",
    variant: "Sonnet",
    APIName: "claude-4-sonnet-20250514",
    provider: "Anthropic",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: true,
      fileUpload: true,
    },
  },
  {
    name: "4.0 Opus",
    baseModel: "4.0",
    variant: "Opus",
    APIName: "claude-4-opus-20250514",
    provider: "Anthropic",
    capabilities: {
      search: false,
      imageUpload: true,
      reasoning: true,
      fileUpload: true,
    },
  },
  // xAI
  {
    name: "3",
    baseModel: "3",
    variant: "",
    APIName: "grok-3-latest",
    provider: "xAI",
    capabilities: {
      search: false,
      imageUpload: false,
      reasoning: false,
      fileUpload: false,
    },
  },
  {
    name: "3 Mini",
    baseModel: "3",
    variant: "Mini",
    APIName: "grok-3-mini-latest",
    provider: "xAI",
    capabilities: {
      search: false,
      imageUpload: false,
      reasoning: true,
      fileUpload: false,
    },
  },
]
